[package]
name = "wopt"
version = "0.1.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/splurf/wopt"
description = "A procedural macro that automatically generates an Option-wrapped version of a struct, reducing boilerplate for optional updates."
keywords = ["proc-macro", "derive", "option", "struct", "automation"]
categories = ["rust-patterns", "data-structures"]
exclude = [".github/", ".gitignore", "LICENSE", "tests/"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
rkyv = { version = "0.8.10", optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
syn = { version = "2.0.100", features = ["derive", "parsing", "proc-macro"] }
proc-macro2 = { version = "1.0.94", default-features = false }

[dev-dependencies]
serde_json = "1.0.140"

[features]
rkyv = ["dep:rkyv"]
serde = ["dep:serde"]

[profile.release]
lto = true
codegen-units = 1
